var k=!1,m=/^bytes [0-9]+-[0-9]+\/([0-9]+)$/,u="object xmlhttprequest media other main_frame sub_frame image".split(" "),w=["object","xmlhttprequest","media","other"],x=/:\/\/.+\/([^/]+?(?:.([^./]+?))?)(?=[?#]|$)/,z=[301,302,303,307,308],A=/^(?:application\/x-apple-diskimage|application\/download|application\/force-download|application\/x-msdownload|application\/octet-stream|binary\/octet-stream)$/i,B=/^(?:FLV|SWF|MP3|MP4|M4V|F4F|F4V|M4A|MPG|MPEG|MPEG4|MPE|AVI|WMV|WMA|WAV|WAVE|ASF|RM|RAM|OGG|OGV|OGM|OGA|MOV|MID|MIDI|3GP|3GPP|QT|WEBM|TS|MKV|AAC|MP2T|MPEGTS|TS|RMVB)$/i,
D=/^(?:HTM|HTML|MHT|MHTML|SHTML|SHTM|XHT|XHTM|XHTML|XML|TXT|CSS|JS|JSON|PDF|GIF|ICO|JPEG|JPG|PNG|WEBP|BMP|SVG|TIF|TIFF|PHP|ASP|ASPX)$/i,E=/^(?:FLV|AVI|MPG|MPE|WMV|QT|MOV|RM|RAM|WMA|MID|MIDI|AAC|MKV|RMVB)$/i,H=/^(?:F4F|MPEGTS|TS|MP2T)$/i,I={"application/x-apple-diskimage":"DMG","application/epub+zip":"EPUB","application/java-archive":"JAR","video/x-matroska":"MKV","text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|SRT","text/srt":"SRT",
"text/vtt":"VTT|SRT","text/xml":"XML|F4M|TTML","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ",
"application/x-gtar":"TAR","application/x-msi":"MSI","application/x-msp":"MSP","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/vnd.apple.installer+xml":"MPKG","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT",
"application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|M3U8","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG|MPE","video/mpegurl":"M3U8|M3U","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U8|M3U",
"video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U8|M3U","image/svg+xml":"SVG|SVGZ","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U8|M3U","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR",
"image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV","image/x-xbitmap":"XBM","audio/x-mp3":"MP3","audio/x-hx-aac-adts":"AAC","audio/aac":"AAC","audio/x-aac":"AAC","application/vnd.rn-realmedia-vbr":"RMVB"};function J(a){return a&&unescape(a.split(";",1).shift().trim())||""}function K(a){return(a=x.exec(a))?a[1]||"":""}
function L(a){return-1<a.indexOf(".")?a.split(".").pop():""}function aa(a){var b;a=a.toUpperCase();for(b in I)if(-1<I[b].split("|").indexOf(a))return b;return""}function M(a,b){if(!a)return null;for(var c=0;c<a.length;c++)if(a[c].name.toLowerCase()==b.toLowerCase())return a[c].value||a[c].binaryValue||null;return null}function N(){for(var a={},b=0;b<arguments.length;b++)for(var c in arguments[b])arguments[b].hasOwnProperty(c)&&(a[c]=arguments[b][c]);return a}
function O(a,b){return a&&b&&0==a.indexOf(b)}function P(a,b){if(!a||!b)return!1;var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function Q(a,b){return a&&b&&0<=a.indexOf(b)}function R(a){return Q(a,"://")?a.split("://",1).shift().toLowerCase()||"":"http"}function ba(a){var b="";a&&(a=a.trim());a&&(b=(new URL(a)).origin);return b}
function S(a,b){var c=b&&b["1"]||"GET",e=new XMLHttpRequest,d;e.open(c,a["2"],!0);e.onreadystatechange=function(){4==e.readyState&&(a.D||function(){})(e.responseText)};e.timeout=15E3;if(b&&(d=b.h))for(var f=0;f<d.length;f++)O(d[f].name.toLowerCase(),"x-")&&e.setRequestHeader(d[f].name,d[f].value);if("POST"==c)try{b["10"]&&e.setRequestHeader("Content-Type",b["10"]),b["11"]&&e.setRequestHeader("Content-Disposition",b["11"]),T(b,b)}catch(h){}e.send(b&&b.postData||null)}
function U(){this["1"]="GET";this["2"]="";this["3"]="";this["4"]="";this["5"]="";this["6"]="normal";this["7"]=0;this["8"]="";this["9"]="";this["10"]="";this.cookies=this["11"]="";this.postData=null}
function V(){var a=this.constructor.prototype,b;for(b in a)this[b]=a[b].bind(this);this.A={};this.a={};this.g={};this.ca=1;this.o=!1;chrome.contextMenus.create({title:"Download by NeatDownloadManager",contexts:["link","image"],onclick:this.S});this.f(chrome.runtime.onConnect,this.W);this.f(chrome.webRequest.onBeforeRequest,this.K,{urls:["http://*/*","https://*/*","ftp://*/*"],types:u},["blocking","requestBody"]);this.f(chrome.webRequest.onBeforeSendHeaders,this.M,{urls:["https://*/*","http://*/*"],
types:u},["blocking","requestHeaders"]);this.f(chrome.webRequest.onHeadersReceived,this.P,{urls:["<all_urls>"],types:u},["blocking","responseHeaders"]);this.f(chrome.webRequest.onResponseStarted,this.j,{urls:["<all_urls>"]});this.f(chrome.webRequest.onCompleted,this.j,{urls:["<all_urls>"]});this.f(chrome.webRequest.onErrorOccurred,this.j,{urls:["<all_urls>"]});this.f(chrome.webNavigation.onHistoryStateUpdated,this.V);chrome.browserAction.onClicked.addListener(this.R);this.u=0;this.H="";var c=this;
this.v=!0;chrome.storage.local.get(["ShowMediaPanel"],function(a){-1==a.ShowMediaPanel&&(c.v=!1)});this.c=this.w=null;this.s=!1;this.G()}var W=V.prototype;W.R=function(a){this.ea(a.id)};W.V=function(a){var b=this.a[[a.tabId,a.frameId]];b&&b["2"]!=a.url&&(b.postMessage([11,a.url]),b["2"]=a.url)};
W.B=function(a){var b=this;if(this.s){var c="1:"+a["1"]+"\r\n";c+="2:"+a["2"]+"\r\n";a["3"]&&(c+="3:"+a["3"]+"\r\n");c+="6:"+(a["6"]||"normal")+"\r\n";a["4"]&&(c+="4:"+a["4"]+"\r\n");a.pageUrl&&(c+="Origin: "+ba(a.pageUrl)+"\r\n");a.pageUrl&&(c+="Referer: "+a.pageUrl+"\r\n");a["5"]&&(c+="5:"+a["5"]+"\r\n");a.cookies&&(c+="Cookie: "+a.cookies+"\r\n");a["10"]&&(c+="Content-Type: "+a["10"]+"\r\n");a["11"]&&(c+="Content-Disposition: "+a["11"]+"\r\n");a["9"]&&(c+="9:"+a["9"]+"\r\n");for(var e in a)O(e.toLowerCase(),
"x-")&&(c+=e+": "+a[e]+"\r\n");"POST"==a["1"]&&(a["7"]&&(c+="7:"+a["7"]+"\r\n"),a["8"]&&(c+="8:"+a["8"]+"\r\n"),c=a.postData?c+("__0NeatPostData9__:"+a.postData):c+"Content-Length: 0\r\n");if(!(102400<c.length))if(a["3"])this.w.send(c),this.c=null,this.u++;else if("POST"==a["1"]||!this.o||a["7"]&&a["8"])"POST"!=a["1"]&&this.o&&(c+="8:"+a["8"]+"\r\n",c+="7:"+a["7"]+"\r\n"),this.w.send(c),this.c=null,this.u++;else{var d=new XMLHttpRequest;d.open("HEAD",a["2"],!0);d.onreadystatechange=function(){4==
d.readyState&&(a["8"]=a["8"]||d.getResponseHeader("Content-Type")||"",a["7"]=a["7"]||d.getResponseHeader("Content-Length")||0,c+="8:"+a["8"]+"\r\n",c+="7:"+a["7"]+"\r\n",b.w.send(c),b.c=null,this.u++)};d.timeout=8E3;d.send()}}else this.c=a,this.G()};W.G=function(){var a=new WebSocket(atob("d3M6Ly8xMjcuMC4wLjE6MTAwMDcvZG93bmxvYWQ="),atob("bmVhdGV4dGVuc2lvbi52MQ=="));a.onopen=this.ba;a.onclose=this.Z;a.onmessage=this.aa;a.onerror=this.$;this.w=a};W.ba=function(){this.s=!0;this.c&&this.B(this.c)};
W.Z=function(){this.s=!1;this.c=null};W.aa=function(a){a=a.data;"waiting"==a?this.o=!0:"nowaiting"==a?this.o=!1:Q(a,"Version")?this.H=a:O(a,"ShowPanelFox")&&(a="1"==a.split("=")[1],a!=this.v&&(this.v=a,chrome.storage.local.set({ga:a?1:-1},function(){}),this.fa([13,a])))};
W.$=function(){this.s=!1;this.c&&alert("Extension Can't Connect to NeatDownloadManager Application.You Can : \r\n1- Check why NeatDownloadManager is not Running.\r\n2- or Hold down Delete-Key and click on your Download link.\r\n3- or Disable NeatDownloadManager Extension temporarily.");this.c=null};W.F=function(a){if(this.c){var b="";if(a&&0<a.length)for(var c=0;c<a.length;c++)b+=a[c].name+"="+a[c].value+(c<a.length-1?"; ":"");b=b.trim();this.c.cookies=b;this.B(this.c)}};
W.S=function(a,b){var c=R(a.linkUrl);!c||"ftp"!=c&&"http"!=c&&"https"!=c||"ftp"==c&&!K(a.linkUrl)||(c=new U,c["2"]=a.linkUrl||a.srcUrl,c.pageUrl=a.pageUrl,c["4"]=b&&b.title||"",b&&b.url&&(c["5"]=b.url),!c["5"]&&(c["5"]=a.pageUrl),this.c=c,chrome.cookies.getAll({url:c["2"]},this.F))};function X(a,b){this.f=a;this.j=b||"m3u8"}
function ca(a,b,c){var e=[],d=0,f="";if("json"==a.j)try{var h=0==b["2"].indexOf("https"),g=JSON.parse(c);g.hls_url&&!h&&e.push({2:g.hls_url,tags:{}});g.https_hls_url&&h&&e.push({2:g.https_hls_url,tags:{}})}catch(F){}if("m3u8"==a.j){c=c.split(/[\r\n]+/);if(0==c.length||"#EXTM3U"!=c[0].trim())return;for(var q=g=h=!1,n="",r=/^#(EXT[^\s:]+)(?::(.*))/,y=1;y<c.length;y++){var p=c[y].trim();p&&("#"==p[0]?0==p.indexOf("#EXT")&&(p=r.exec(p))&&(h||(h="EXTINF"==p[1])&&(n=p[2]),g||(g="EXT-X-STREAM-INF"==p[1])&&
(n=p[2]),q||(q="EXT-X-BYTERANGE"==p[1])):(h&&(d+=parseFloat(n),h=!1),g&&(e.push({2:(new URL(p,b["2"])).href,tags:n}),g=!1),q&&!f&&(f=(new URL(p,b["2"])).href)))}}if(f){c="";d&&(60<d&&(c+=parseInt(d/60)+" min "),c+=parseInt(d%60)&&parseInt(d%60)+" sec");var l={6:"media",fileExtension:"ts",4:"TS File "+c,fileDuration:c};l=N(l,{1:b["1"],2:f,tabId:b.tabId,frameId:b.frameId,fileSize:b["7"],fileName:b.fileName});Y(b,l);"POST"==l["1"]&&T(b,l);setTimeout(function(){a.f.l(l)},3E3)}else e.length?setTimeout(function(){for(var c=
0;c<e.length;c++){var d=e[c].tags;var f="";if(d){if((d=d.split(","))&&d.length)for(var g=0;g<d.length;g++){var h=d[g].split("=");h&&2==h.length&&("BANDWIDTH"==h[0].toString().trim()&&(f+=parseInt(parseInt(h[1])/1024)+" Kbps "),"RESOLUTION"==h[0].toString().trim()&&(f+=h[1]+" "))}f=f.trim()}a.f.l(N({tabId:b.tabId,frameId:b.frameId},{1:"GET",2:e[c]["2"],6:"hls",fileExtension:"ts",4:"TS File "+f}))}},3E3):0<d&&(c="",60<d&&(c+=parseInt(d/60)+" min "),c+=parseInt(d%60)&&parseInt(d%60)+" sec",l={6:"hls",
fileExtension:"ts",4:"TS File "+c,fileDuration:c},l=N(l,{1:b["1"],2:b["2"],tabId:b.tabId,frameId:b.frameId,fileSize:b["7"],fileName:b.fileName}),Y(b,l),"POST"==l["1"]&&T(b,l),setTimeout(function(){a.f.l(l)},3E3))}W.l=function(a){var b=this.a[[a.tabId,a.frameId]];if(!b&&(b=this.a[[a.tabId,0]],!b))return;var c=a["2"],e=0,d;var f=0;for(d=c.length;f<d;f++){var h=c.charCodeAt(f);e=(e<<5)-e+h;e|=0}a.id=e;b.postMessage([1,a,b["2"]])};W.j=function(a){delete this.g[a.requestId]};
function da(a,b){if(!a)return null;var c=a.raw;if(c){a="";for(b=0;b<c.length;b++){var e=c[b].ha;if(!e)return null;e=new Uint8Array(e);for(var d=e.length,f=0;f<d;f++)a+=String.fromCharCode(e[f])}return a}c=a.formData;if(!c)return null;d=J(b);a=[];d&&(d=d.toLowerCase());if("application/x-www-form-urlencoded"==d){for(e in c)for(d=c[e],e=e.split(" ").map(encodeURIComponent).join("+"),b=0;b<d.length;b++)a.length&&a.push("&"),a.push(e,"=",d[b].split(" ").map(encodeURIComponent).join("+"));return a.join("")}if("multipart/form-data"==
d){(f=Z(b,"boundary"))||(f="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(e in c)for(d=c[e],b=0;b<d.length;b++)a.push("--",f,'\r\nContent-Disposition: form-data; name="',e,'"\r\n\r\n',d[b],"\r\n");a.push("--",f,"--\r\n");return a.join("")}return null}
W.L=function(a){if(!("video/webm"!=a["8"].toLowerCase()&&"audio/webm"!=a["8"].toLowerCase()||1>a["2"].indexOf("signature=")&&1>a["2"].indexOf("sig="))){var b=this.a[[a.tabId,a.frameId]];b||(b=this.a[[a.tabId,0]]);if(b){var c=a["2"].indexOf("?");if(-1!=c){var e=a["2"].substring(0,c),d=a["2"].substring(c+1);c={2:"",mime:a["8"].split("/").shift(),itg:0,du:0,mKey:"",purl:b["2"]};"video/webm"==a["8"].toLowerCase()&&Y(a,c);a=e+"?";e=d.split("&");for(d=0;d<e.length;d++)O(e[d],"dur=")&&(c.du=parseFloat(e[d].split("=").pop())),
O(e[d],"itag=")&&(c.itg=e[d].split("=").pop()),O(e[d],"ei=")&&(c.mKey=e[d].split("=").pop()),O(e[d],"range=")||O(e[d],"rbuf=")||O(e[d],"rn=")||(a=a+e[d]+"&");c.du&&c.itg&&(a=a.substring(0,a.length-1),c["2"]=a,b.postMessage([9,c]))}}}};
W.P=function(a){var b,c=a.requestId,e=this;if(b=this.g[c]){var d=a.url,f=a.type,h=0<=w.indexOf(f),g=a.method.toUpperCase(),q=R(d);if(!q||"http"!=q&&"https"!=q||"GET"!=g&&"POST"!=g)delete this.g[c];else{b.m=a.responseHeaders;var n=M(b.m,"Content-Type"),r=J(n).toLowerCase();if("image"==f&&r&&O(r.toLowerCase(),"image/"))delete this.g[c];else{var y=M(b.m,"Content-Disposition"),p="attachment"==J(y).toLowerCase();a=parseInt(a.statusLine.split(" ",2).pop())||0;b.T=0<=z.indexOf(a);if(!b.T){if(200==a||206==
a){a=M(b.m,"Content-Length");var l=M(b.m,"Content-Range"),F=null;l&&(l=m.exec(l))&&(a=l[1]);a&&(F=parseInt(a));if(0!==F){b["2"]=d;b["8"]=n;b["7"]=F;b.type=f;b.protocol=q;b["1"]=g;b.J=P(f,"_frame");g=new URL(d);f=g.hostname;g=g.pathname;(q=g.split("/").pop().trim())&&(q=q.split("?").shift().trim());b.i=q||"";b.I=L(b.i);b.C=Z(y,"filename")||Z(n,"name");b.O=b.C&&L(b.C)||"";n=r?I[r]:!1;b.N=(n?n.split("|").shift():"").toLowerCase();b.b=b.N||b.O||b.I||"";b.fileName=b.C||b.i||"";b.fileName&&(n=b.fileName.lastIndexOf("."),
-1<n&&(b.fileName=b.fileName.substr(0,n).trim()));b.fileName&&b.b&&(b.fileName+="."+b.b);!r&&b.b&&(r=aa(b.b));if(!(Q(b.i.toLowerCase(),".webmanif")||Q(b.i.toLowerCase(),"manifest.json")||Q(b.i.toLowerCase(),"favicon.ico")||P(b.i.toLowerCase(),".wasm")||Q(b.i.toLowerCase(),"site.json"))&&("other"==b.type&&B.test(b.b)||(b.J||!h)&&E.test(b.b)||(b.J||"other"==b.type)&&(p||A.test(r)||b.b&&!B.test(b.b)&&!D.test(b.b)))){if(b.isKeyDown){delete this.g[c];return}var t=e.a[[b.tabId,b.frameId]];d=e.a[[b.tabId,
0]];var v=N(new U,{2:b["2"],1:b["1"],4:d&&d["4"]||t&&t["4"],5:d&&d["2"]||t&&t["2"],7:b["7"],8:b["8"],pageUrl:t&&t["2"]||b["2"]});chrome.tabs.query({active:!0,currentWindow:!0},function(a){if(b["2"]==a[0].url){if(!v["5"]&&a[0].openerTabId){var c=e.a[[a[0].openerTabId,0]];v["5"]=c&&c["2"];v["4"]=c&&c["4"]}chrome.tabs.remove(a[0].id)}});"POST"==v["1"]&&T(b,v);Y(b,v);e.c=v;chrome.cookies.getAll({url:v["2"]},e.F);delete this.g[c];return{redirectUrl:"javascript:"}}var C=null;"m3u8"==b.b.toLowerCase()||
"m3u8"==b.I.toLowerCase()?C=new X(this):(new RegExp(atob("Xmh0dHBzPzovL2FwaVwucGVyaXNjb3BlXC50di9hcGkvdjIvZ2V0QWNjZXNzUHVibGlj"))).test(d)?C=new X(this,"json"):"POST"==b["1"]||Q(f.toLowerCase(),atob("dmltZW8="))||Q(f.toLowerCase(),atob("eW91dHViZQ=="))||Q(f.toLowerCase(),"google")||"txt"!=b.b.toLowerCase()&&"js"!=b.b.toLowerCase()||"xmlhttprequest"!=b.type||b["7"]&&262144<b["7"]||(C=new X(this));if(C)S({2:b["2"],D:function(a){ca(C,N({},b),a)}},N({},b));else if(h&&P(f,atob("Z29vZ2xldmlkZW8uY29t"))&&
O(g,atob("L3ZpZGVvcGxheWJhY2s=")))this.L(b);else if(h&&(new RegExp(atob("Xig/Olt3LV0rLikqPyg/OnlvdXR1YmUuY29tfGdvb2dsZXZpZGVvLmNvbXx5b3V0dWJlLmdvb2dsZWFwaXMuY29tfGRvY3MuZ29vZ2xlLmNvbSkk"),"i")).test(f))(P(g,atob("L2dldF92aWRlb19pbmZv"))||P(g,atob("YXBpX3ZpZGVvX2luZm8=")))&&"application/x-www-form-urlencoded"==r&&0!=b.frameId&&S({2:b["2"],D:function(a){a=decodeURIComponent(a);for(var c,d,f=["formats"],h=0;h<f.length;h++){var g=a;c=g.indexOf(f[h]);0>c||(g=g.substr(c),c=g.indexOf("["),d=g.indexOf("]"),
0>c||0>d||d<=c||(g=g.substr(c+1,d-c-1),(t=e.a[[b.tabId,b.frameId]])||(t=e.a[[b.tabId,0]]),t&&t.postMessage([7,g])))}}},b);else if(h&&f==atob("cGxheWVyLnZpbWVvLmNvbQ==")&&O(g,"/video/")&&"application/json"==r)S({2:b["2"],D:function(a){var c=null;try{c=JSON.parse(a)}catch(ea){}if(c){var d=c.request.files.progressive;d&&setTimeout(function(){for(var a=0;a<d.length;a++)e.l({1:"GET",2:d[a].url,6:"media",tabId:b.tabId,frameId:b.frameId,fileExtension:"mp4",4:"MP4 File "+d[a].quality})},3E3)}}},b);else if(!(!h||
!B.test(b.b)||H.test(b.b)||b["7"]&&65536>b["7"]||"ASF"==b.b&&655360>=b["7"]||"DCLK-AdSvr"==M(b.m,"Server"))){var G={2:b["2"],6:"media",1:b["1"],tabId:b.tabId,frameId:b.frameId,fileExtension:b.b,7:b["7"],8:b["8"],fileSize:b["7"],fileName:b.fileName};"POST"==G["1"]&&T(b,G);Y(b,G);setTimeout(function(){e.l(G)},3E3)}}}delete this.g[c]}}}}};
function T(a,b){var c=M(a.h,"Content-Type"),e=M(a.h,"Content-Disposition");a=da(a.da,c);if(!a||1>a.length)a=null;b.postData=a;c&&(b["10"]=c.trim());e&&(b["11"]=e.trim())}function Y(a,b){if(a.h)for(var c=0;c<a.h.length;c++)O(a.h[c].name.toLowerCase(),"x-")&&(b[a.h[c].name]=a.h[c].value)}W.M=function(a){if(!(0>a.tabId||0>a.frameId)){var b=this.g[a.requestId];b&&(b.isKeyDown=k,b.h=a.requestHeaders)}};
W.K=function(a){if(!(0>a.tabId||0>a.frameId))if("ftp"==R(a.url)){if(K(a.url)&&!k){var b=new U,c=this.a[[a.tabId,0]];c&&c["2"]&&(b["5"]=c["2"],b.pageUrl=c["2"]);c&&c["4"]&&(b["4"]=c["4"]);b["2"]=a.url;this.B(b);return{redirectUrl:"javascript:"}}}else b=a.requestId,c=this.g[b]||{id:b,2:a.url,tabId:a.tabId,frameId:a.frameId},"POST"==a.method.toUpperCase()&&(c.da=a.requestBody),c.isKeyDown=k,this.g[b]=c};
function Z(a,b){if(!a)return null;b=b.toLowerCase();a=a.split(";");a.shift();for(var c=0;c<a.length;c++){var e=a[c],d=e.indexOf("=");if(0<d){var f=e.substr(0,d).trim().toLowerCase(),h="*"==f[f.length-1];h&&(f=f.substr(0,f.length-1).trimRight());if(f==b)return a=e.substr(d+1).trim(),c=a.length-1,'"'==a[0]&&'"'==a[c]&&(a=a.substring(1,c)),h&&(a=a.split("'",3).pop()),unescape(a)}else if(0>d&&e.trim().toLowerCase()==b)return""}return null}W.f=function(a){a.addListener.apply(a,Array.prototype.slice.call(arguments).slice(1))};
W.W=function(a){var b=a.sender.tab;if(b&&0<=b.id){var c=a.sender.frameId,e=a.id||this.ca++,d=b.id;a.id=e;a["4"]=b.title;a.tabId=d;a.frameId=c;a.U=0==c;a["2"]=a.sender.url||a.U&&b.url||null;a.onMessage.addListener(this.Y.bind(this,a));a.onDisconnect.addListener(this.X.bind(this,a));this.A[e]=a;this.a[[d,c]]=a;a.postMessage([3,a.id]);a.postMessage([13,this.v]);a.postMessage([15,1==this.u%2?this.H:"X1"]);a.sender=null}};
W.Y=function(a,b){switch(b[0]){case 2:var c=b[2],e=b[3];(a=this.A[b[1]])&&c&&(a["2"]=c);a&&e&&(a["4"]=e);break;case 4:k=b[1];break;case 6:c=b[1];a=(a=a.tabId)&&this.a[[a,0]];var d=new U;d["1"]=c["1"]||"GET";d["2"]=c["2"];c["3"]&&(d["3"]=c["3"]);d.pageUrl=b[2];d["4"]=b[3]||a&&a["4"]||"";d["5"]=a&&a["2"]||d.pageUrl;d["9"]=b[4];c["7"]&&(d["7"]=c["7"]);c["8"]&&(d["8"]=c["8"]);d["6"]=c["6"]||"media";c.postData&&(d.postData=c.postData);c["10"]&&(d["10"]=c["10"]);c["11"]&&(d["11"]=c["11"]);for(e in c)O(e.toLowerCase(),
"x-")&&(d[e]=c[e]);this.c=d;chrome.cookies.getAll({url:d["2"]},this.F)}};W.X=function(a){for(var b in this.a)this.a[b]==a&&delete this.a[b];delete this.A[a.id]};W.ea=function(a){var b=[5],c=this.a;a=a.toString()+",";for(var e in c)O(e,a)&&c[e].postMessage(b)};W.fa=function(a){var b=this.a,c;for(c in b)b[c].postMessage(a)};new V;
