var C=chrome.extension.getURL("img/icon16.png"),D=chrome.extension.getURL("img/close16.png"),E={"-1":"none",1:""},F={242:"240p",243:"360p",244:"480p",246:"480p",247:"720p",248:"1080p",271:"1440p",272:"2160p",278:"144p",302:"720p",303:"1080p"};function G(a){return document.getElementById(a)}window.el=G;function H(){var a=document.location.host.toLowerCase(),b=atob("ZmFjZWJvb2suY29t"),c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function N(a){return"0"<=a&&"9">=a}
function O(a){var b=new XMLHttpRequest;b.timeout=3E4;b.open("GET",a["2"],!0);b.onreadystatechange=function(){4==b.readyState&&(a.pa||function(){})(b.responseText)};b.send()}function P(a){var b=0,c;var d=0;for(c=a.length;d<c;d++){var e=a.charCodeAt(d);b=(b<<5)-b+e;b|=0}return b}function Q(a){return a.replace(/\\u([\d\w]{4})/gi,function(a,c){return String.fromCharCode(parseInt(c,16))})}
function R(a){if(!a)return{left:0,top:0};try{var b=a.getBoundingClientRect();return b?{left:Math.round(b.left+window.pageXOffset),top:Math.round(b.top+window.pageYOffset)}:null}catch(c){return null}}function S(a){if(a){var b;(b=a["4"])||(b=a.fileSize,b=(a.fileExtension.toUpperCase()||"MP4")+" File  "+((!b||0>b?" ":1E3>b?b+" Bytes":1E6>b?(b/1E3).toFixed(1)+" KB":1E9>b?(b/1E6).toFixed(2)+" MB":(b/1E9).toFixed(3)+" GB")||a.fileDuration));a=b}else a="";return a}
function T(a,b,c){this.o=a;a.c[c]=this;this.L=c;this.C="neatTable"+c;this.H="neatHCell"+c;this.b=null;this.h=b;this.position={left:0,top:0};this.displayMode=-1;this.items=[];this.K=this.J=0;this.i=this.B=!1}var U=T.prototype;U.u=function(a){var b=Array.prototype.slice.call(arguments);b[2]=b[2].bind(this);a.addEventListener.apply(a,b.slice(1))};U.l=function(){this.b&&(this.b.style.left=this.position.left+"px",this.b.style.top=this.position.top+"px",this.b.style.zIndex+=500)};
U.T=function(a){this.D(!0);this.o.la(this.items[a])};U.D=function(a){if(!a||-1!=this.displayMode){var b=G(this.C).rows;this.displayMode=a?-1:-this.displayMode;for(a=1;a<b.length;a++)b[a].style.display=E[this.displayMode]}};
U.A=function(a){var b=this,c=this.o.G(this.items[a]);var d=G(this.C).insertRow(-1);d.cssText="all:revert;padding:0px;margin:0px;width:100%;line-height:100% !important;height:21px !important";d.style.display=E[b.displayMode];var e=d.insertCell(0);e.style.cssText="all:revert;letter-spacing:normal;line-height:100% !important;width:100%;height:21px !important;margin:0px;padding:0px;padding-left:5px;vertical-align:middle;color:black !important;cursor:default;border:dotted 1px black;background:#e6f6fd !important;direction:ltr;text-align:left;font-family:tahoma !important;font-style:normal;font-weight:bold;font-size:8pt !important;";c=
S(c);0==a&&1==this.items.length?(e.innerHTML=("<table style='all:revert;border-spacing:0px;border-collapse:separate;padding:0px;margin:0px;width:100%;border:solid 1px black;direction:ltr;line-height:100% !important;'><tr style='all:revert;padding:0px;margin:0px;line-height:100% !important;height:21px !important'><td style='all:revert;background:#e6f6fd !important;padding:0px;margin:0px;width:20px;height:21px !important;text-align:center;vertical-align:middle;line-height:100% !important;'><img onclick='alert(\"NeatDownloadManager Video/Audio Panel.\")'  src='"+
C+"'/></td><td id='HeaderCellID' style='all:revert;letter-spacing:normal;padding:0px;margin:0px;vertical-align:middle;color:black !important;cursor:default;background:#e6f6fd !important;direction:ltr;text-align:center;font-family:tahoma !important;font-style:normal;font-weight:bold;font-size:8pt !important;height:21px !important;line-height:100% !important;'></td><td style='all:revert;background:#e6f6fd !important;padding:0px;margin:0px;width:20px;height:21px !important;text-align:center;vertical-align:middle;line-height:100% !important;'><img id='CloseImgID' src='"+
D+"'/></td></tr></table>").replace("HeaderCellID",b.H).replace("CloseImgID","CloseImg"+b.L),e.style.paddingLeft="0px",d=G(b.H),d.innerText=" "+c,d.onmouseover=function(){this.style.color="red"},d.onmouseout=function(){this.style.color="black"},d.onclick=function(){0==b.i&&b.T(0);b.i=!1},G("CloseImg"+b.L).onclick=function(){b.b.style.display="none"}):(e.innerText=" "+(a+1).toString()+"- "+c,e.onmouseover=function(){this.style.background="white";this.style.color="red"},e.onmouseout=function(){this.style.background=
"#e6f6fd";this.style.color="black"},d.onmousedown=function(){b.T(a)})};
U.F=function(a){var b=this,c=this.o.G(a),d=null,e=this.h?"absolute":"fixed";this.h&&!this.B&&(d=R(this.h));d&&(this.position={left:Math.max(0,d.left),top:Math.max(0,d.top-21)});this.b?this.l():(this.b=document.createElement("DIV"),this.b.style.cssText="all:revert;padding:0px;margin:0px;position:"+e+";z-index:100000000;width:228px;left:"+this.position.left+"px;top:"+this.position.top+"px;direction:ltr;text-align:center;background:#e6f6fd !important;line-height:100% !important;",this.b.id="neatDiv"+
this.L,this.b.style.display=this.o.w?"":"none",document.body.appendChild(this.b),d=document.createElement("TABLE"),d.id=this.C,d.style.cssText="all:revert;border-spacing:0px;border-collapse:separate;padding:0px;margin:0px;line-height:100% !important;direction:ltr;width:100%;",this.b.appendChild(d),this.u(b.b,"mousemove",b.ra),this.u(b.b,"mousedown",b.qa),this.u(b.b,"mouseup",b.v),this.u(b.b,"mouseout",b.v),this.u(b.b,"mouseover",b.v));if(!(-1<this.items.indexOf(a)&&"hls"!=c["6"])){c=S(c);if(this.items.length&&
(" MP4 File HQ"==c||" MP4 File LQ"==c))for(d=0;d<this.items.length;d++)if(c==S(this.o.G(this.items[d]))){this.items[d]=a;this.b.style.display=this.o.w?"":"none";this.l();return}this.items.push(a);a=this.items.length-1;c=G(b.C).rows;var h;a&&(h=G(b.H));0==a?this.A(0):1==a?(this.A(0),this.A(1),h.onclick=function(a){a.stopPropagation();a.preventDefault();0==b.i&&b.D();b.i=!1},h.innerText=" 2 Files"):(this.A(a),h.innerText=" "+(a+1).toString()+" Files");c[0].style.display=""}};
U.qa=function(a){0==a.button&&(this.B=!0,this.i=!1,this.J=a.clientX,this.K=a.clientY,a.stopPropagation(),a.preventDefault())};U.ra=function(a){if(this.B){this.D(!0);var b=a.clientX-this.J,c=a.clientY-this.K;!this.i&&(this.i=b||c);this.position.left+=b;this.position.top+=c;this.J=a.clientX;this.K=a.clientY;this.l()}else this.i=!1};U.v=function(){this.B=!1};
if(!window.f){var V=function(a){a=R(a.h);return!a||0>a.left||0>a.top},W=function(a,b){return 10>Math.abs(a.left-b.left)&&10>Math.abs(a.top-b.top)},X=function(){this.X=null;this.j={};this.c={};this.a=[];this.I=!1;this.V=this.U=-1;this.Counter=1;this.g=null;this.w=!0;this.R="";this.Z=0;this.S=[];this.port=chrome.runtime.connect({name:"neat"});this.aa=Math.ceil(2E6*Math.random());this.port.onMessage.addListener(this.ja.bind(this));this.port.onDisconnect.addListener(this.ma.bind(this));if(H()){var a=
this;this.ha=new window.MutationObserver(function(b){b.forEach(function(b){a.ca(b.target)})});this.ha.observe(document,{childList:!0,subtree:!0})}this.f(window,"keydown",this.O,!0);this.f(window,"keyup",this.O,!0);this.f(window,"mouseup",this.v,!0);this.f(window,"resize",this.oa);this.f(document,"DOMContentLoaded",this.W);this.f(document,"click",this.ea)};window.f=!0;U=X.prototype;U.na=function(a,b){b.hd&&this.m({id:P(b.hd),1:"GET",2:b.hd,fileExtension:"mp4",4:" MP4 File HQ"},window.location.href,
a,!1);b.sd&&this.m({id:P(b.sd),1:"GET",2:b.sd,fileExtension:"mp4",4:" MP4 File LQ"},window.location.href,a,!1)};U.ga=function(a){for(;(a=a.parentElement)&&1>a.querySelectorAll("video").length;);if(a)return a.querySelectorAll("video")[0]};U.da=function(a,b){var c=this;O({2:"https://www.facebook.com/video/embed?video_id="+b,pa:function(b){var d=/"sd_src_no_ratelimit":"(.*?)"/.exec(b),h=/"hd_src_no_ratelimit":"(.*?)"/.exec(b);d&&d.length||(d=/"sd_src":"(.*?)"/.exec(b));h&&h.length||(h=/"hd_src":"(.*?)"/.exec(b));
b={sd:d&&d.length?d[1].replace(/\\/g,""):"",hd:h&&h.length?h[1].replace(/\\/g,""):""};d=c.ga(a);void 0!==d&&c.na(d,b)}})};U.ca=function(a){var b=this;a=a.querySelectorAll('a[href*="/videos/"]');a.length&&Array.from(a,function(a){if(!a.getAttribute("NEAT_DM")){a.setAttribute("NEAT_DM",1);var c=a.href.match(/.*\/videos\/(\d+)\/.*/i);c&&b.da(a,c[1])}})};U.G=function(a){return this.j[a]};U.ta=function(){this.port.postMessage([2,this.X,window.location.href,this.getTitle()])};U.W=function(a){for(var b=
this,c=document.getElementsByTagName("SCRIPT"),d,e,h,k=!1,g=new RegExp(atob("KD86eXRwbGF5ZXJcLmNvbmZpZ1xzKj18J1BMQVlFUl9DT05GSUcnXHMqOilccypcew==")),n=new RegExp(atob("InByb2dyZXNzaXZlIjpccypcWw==")),m=0;m<c.length;m++){var p=c[m];if(a&&!k&&!p.src&&g.test(p.innerText)){a=["formats"];for(c=0;c<a.length;c++)if(d=p.innerText,e=d.indexOf(a[c]),!(0>e||(d=d.substr(e),e=d.indexOf("["),h=d.indexOf("]"),0>e||0>h||h<=e||(d=d.substr(e+1,h-e-1),!this.P(d))))){k=!0;break}break}if(0<=document.location.host.toLowerCase().indexOf("vimeo")&&
!p.src&&n.test(p.innerText)&&(d=p.innerText,e=d.indexOf('"progressive"'),!(0>e||(h=d.indexOf("]",e),0>h)))){d=d.substr(e,h-e+1);e=null;try{e=JSON.parse("{"+d+"}")}catch(x){}if(e){var q=e.progressive;q&&setTimeout(function(){for(var a=0;a<q.length;a++)b.m({id:P(q[a].url),1:"GET",2:q[a].url,fileExtension:"mp4",4:"MP4 File "+q[a].quality},window.location.href,null,!1)},3E3);break}}}};U.P=function(a){var b=this,c={5:{e:"flv",s:"240p"},17:{e:"3gp",s:"144p"},18:{e:"mp4",s:"360p"},22:{e:"mp4",s:"720p"},
34:{e:"flv",s:"360p"},35:{e:"flv",s:"480p"},36:{e:"3gp",s:"240p"},37:{e:"mp4",s:"1080p"},38:{e:"mp4",s:"1080p"},43:{e:"webm",s:"360p"},44:{e:"webm",s:"480p"},45:{e:"webm",s:"720p"},46:{e:"webm",s:"1080p"},82:{e:"mp4",s:"360p"},84:{e:"mp4",s:"720p"},100:{e:"webm",s:"360p"},102:{e:"webm",s:"720p"}};a=Q(a);a=a.replace(/\\/g,"");var d=[],e="";a=a.split("}");if(!(1>a.length)){for(var h=0;h<a.length;h++){var k=a[h].trim();if(k){var g=k.indexOf('"url"');if(!(0>g)){var n={};g=k.indexOf('"',g+5);var m=k.indexOf('"',
g+1);if(!(0>g||0>m||m<=g||(n.url=decodeURIComponent(k.substr(g+1,m-g-1)),g=k.indexOf('"itag"'),0>g))){for(g+=6;!N(k[g]);)g++;for(m="";N(k[g]);)m+=k[g],g++;n.itag=parseInt(m);n.url&&n.itag&&c[n.itag]&&(0<n.url.indexOf("signature=")||0<n.url.indexOf("sig="))&&(k="",g=n.url,m=g.indexOf("dur="),0<m&&(g=g.substr(m+4),g=g.split("&").shift(),g=parseInt(g))&&(e=k=60>g?g+" sec":parseInt(g/60)+" min "+(parseInt(g%60)?parseInt(g%60)+" sec":"")),n.timeStr=k,d.push(n))}}}}if(!d.length)return!1;this.sa();setTimeout(function(){for(var a=
0;a<d.length;a++){var g=d[a];b.m({id:P(g.url),itg:g.itag,1:"GET",2:g.url,fileExtension:c[g.itag].e,4:c[g.itag].e+" File "+c[g.itag].s+", "+(g.timeStr||e)},window.location.href,null,!1)}},2E3);return!0}};U.sa=function(){this.a=[];for(var a in this.c)for(var b=this.c[a],c=0;c<b.items.length;c++){var d=this.j[b.items[c]];if(d&&d.itg){this.M(a,!0);break}}};U.M=function(a,b){var c=this.c[a];if(c){if(b)for(b=0;b<c.items.length;b++)delete this.j[c.items[b]];try{document.body.removeChild(c.b)}catch(d){}delete this.c[a]}};
U.la=function(a){(a=this.j[a])&&this.port.postMessage([6,a,window.location.href,this.getTitle(),S(a)]);this.Z++;1==this.Z&&""==this.R&&alert("You are Using an Old Version of\r\nNeat Download Manager\r\n\r\nGet the New version from neatdownloadmanager.com ")};U.fa=function(a,b){var c=null,d=["VIDEO","AUDIO","OBJECT","EMBED"];try{var e=document.activeElement,h=0,k,g,n=e&&0<=d.indexOf(e.tagName)?e:null;n||(n=(e=document.elementFromPoint(this.U,this.V))&&0<=d.indexOf(e.tagName)?e:null);for(var m=0;m<
d.length;m++){for(var p=document.getElementsByTagName(d[m]),q=0;q<p.length;q++)if(e=p[q],3!=m||atob("YXBwbGljYXRpb24veC1zaG9ja3dhdmUtZmxhc2g=")==e.type.toLowerCase()){var x=e.src||e.data;if(x&&(x==a||x==b)){var I=e;break}if(n||J)var J=e;else{var y=e.clientWidth,z=e.clientHeight;if(y&&z){var K=window.getComputedStyle(e);if(!K||"hidden"!=K.visibility){var L=y*z;z<1.4*y&&y<3*z&&L>h&&(h=L,k=e);g||(g=e)}}}}if(I)break}(c=I||n||J||k||g)||(c=document.querySelectorAll("video,audio")[0]);if(!c)return null;
if("EMBED"==c.tagName&&!c.clientWidth&&!c.clientHeight){var M=c.parentElement;"OBJECT"==M.tagName&&(c=M)}return c}catch(Y){return null}};U.ia=function(a){try{var b=parseInt(a.getAttribute("JM_NEAT"));b||(b=this.aa<<10|this.Counter++,a.setAttribute("JM_NEAT",b));return b}catch(c){}};U.getTitle=function(){var a="";try{a=document.title||document.getElementsByTagName("title")[0].innerText,a=a.trim()}catch(b){}return a?a=a.replace(/[ \t\r\n\u25B6]+/g," ").trim():""};U.O=function(a){8!=a.keyCode&&46!=a.keyCode||
this.port.postMessage([4,"keydown"==a.type])};U.v=function(a){0==a.button&&(this.U=a.clientX,this.V=a.clientY)};U.oa=function(){if(!this.I){this.I=!0;var a=this;window.setTimeout(function(){for(var b in a.c){var c=a.c[b],d=null;c.h&&(d=R(c.h));if(d){try{document.body.removeChild(c.b)}catch(e){}c.position.left=Math.max(0,d.left);c.position.top=Math.max(0,d.top-21);document.body.appendChild(c.b)}c.l()}a.I=!1},500)}};U.m=function(a,b,c,d){var e=this,h=-1,k=null,g;d=d&&(new RegExp(atob("LipmYWNlYm9vay5jb20kfC4qdmltZW8uY29tJHwuKnlvdXR1YmUuY29tJA=="),
"i")).test(window.location.host)&&!(!a.fileSize||4194304<a.fileSize);a.id||(a.id=P(a["2"]));c||(c=this.fa(a["2"],b));if(!c)for(g in this.c){k=this.c[g];h=g;break}if(!c&&!k){if(d)return;k=new T(e,null,0)}else if(!k)if(h=this.ia(c),k=this.c[h],!k){if(d)return;k=new T(e,c,h);b=R(c);c={left:Math.max(0,b.left),top:Math.max(0,b.top-21)};for(g in this.c)if(g&&g!=h&&(b=this.c[g],W(c,b.position))){for(c=0;c<b.items.length;c++)k.F(b.items[c]);this.M(g,!1);break}if(0!=h&&this.c[0]){b=this.c[0];for(c=0;c<b.items.length;c++)k.F(b.items[c]);
this.M(0,!1)}}else{if(d){k.l();return}}else if(d){k.l();return}h=S(a);for(g=0;g<k.items.length;g++)if(b=S(e.j[k.items[g]]),0==h.trim().indexOf("TS File")&&h==b)return;e.j[a.id]=a;k.F(a.id);k.h&&V(k)&&!this.g&&(e.g=setInterval(function(){e.ba(k)},1500))};U.ba=function(a){if(a&&a.h){var b=R(a.h);b&&(a.position={left:Math.max(0,b.left),top:Math.max(0,b.top-21)},a.l());!b||0>b.left||0>b.top||(clearInterval(this.g),this.g=null)}else clearInterval(this.g),this.g=null};U.N=function(a,b){var c=this,d=a.du,
e="";e=60>d?parseInt(d)+" sec":parseInt(d/60)+" min "+(parseInt(d%60)?parseInt(d%60)+" sec":"");var h={id:P(a["2"]+b["2"]),2:a["2"],3:b["2"],itg:a.itg,4:"MKV File "+F[a.itg]+", "+e},k;for(k in a)0==k.toLowerCase().indexOf("x-")&&(h[k]=a[k]);setTimeout(function(){c.m(h,a.purl,null,!1)},3E3)};U.ka=function(a){var b;if("video"!=a.mime||F[a.itg]){for(b=0;b<this.a.length;b++)if(a.itg==this.a[b].itg&&(a.mKey==this.a[b].mKey||2>Math.abs(a.du-this.a[b].du)))return;a.used=!1;if("video"==a.mime){var c=null;
for(b=0;b<this.a.length;b++)if("audio"==this.a[b].mime&&!this.a[b].used&&(a.mKey==this.a[b].mKey||2>Math.abs(a.du-this.a[b].du))){this.a[b].used=!0;c=this.a[b];break}if(!c)for(b=0;b<this.a.length;b++)if("audio"==this.a[b].mime&&(a.mKey==this.a[b].mKey||2>Math.abs(a.du-this.a[b].du))){this.a[b].used=!0;c=this.a[b];break}c&&(a.used=!0,this.N(a,c))}else{c=null;for(b=0;b<this.a.length;b++)if("video"==this.a[b].mime&&0==this.a[b].used&&(a.mKey==this.a[b].mKey||2>Math.abs(a.du-this.a[b].du))){this.a[b].used=
!0;c=this.a[b];break}c&&(a.used=!0,this.N(c,a))}this.a.push(a)}};U.ja=function(a){var b=this;switch(a[0]){case 1:b.m(a[1],a[2],null,!0);break;case 3:var c=a[1];c&&(b.X=c);b.ta();break;case 5:b.$();break;case 7:b.P(a[1]);break;case 9:setTimeout(function(){b.ka(a[1])},2E3);break;case 11:b.Y();c=window.location.href;if(0<=(new URL(c)).hostname.toLowerCase().indexOf(atob("eW91dHViZS4="))){c=a[1];2<c.length&&"#"==c.charAt(c.length-2)?c=c.substr(0,c.length-1)+(parseInt(c.substr(c.length-1))+1)%10:c+="#0";
window.location.replace(c);break}setTimeout(function(){b.W()},4E3);break;case 13:c=a[1];c!=b.w&&(b.w=c,b.$());break;case 15:b.R=a[1]}};U.f=function(a){var b=Array.prototype.slice.call(arguments);b[2]=b[2].bind(this);this.S.push(b);a.addEventListener.apply(a,b.slice(1))};U.ea=function(){for(var a in this.c)this.c[a].D(!0)};U.Y=function(){try{for(var a in this.c)document.body.removeChild(this.c[a].b)}catch(b){}this.c={};this.j={};this.a=[];this.g&&clearInterval(this.g);this.g=null};U.$=function(){var a=
this.w?"":"none";try{for(var b in this.c)this.c[b].b.style.display=a}catch(c){}};U.ma=function(){for(var a;a=this.S.shift();){var b=a.shift();b.removeEventListener.apply(b,a)}this.Y();this.port=null;window.f=!1};new X};
